name: make-distro-emerge
run-name: ${{ github.actor }} is generating Yocto based Linux distro
on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build Yocto Rootfs
      run: |
        pwd
        ls
        source yocto/sources/poky/oe-init-build-env build
        bitbake stephendpmurphy-image
    - name: Compress the output images
      run: |
        tar -czvf images.tar.gz -C ./tmp/deploy/images/stm32mp1 .